<script src="{{ asset('js/app.js') }}" defer></script>
<script src="https://kit.fontawesome.com/4d3b8c129c.js"></script>
<script src="{{ asset('js/main.js') }}" defer></script>
<script src="{{ asset('js/idleTimer.min.js') }}" defer></script>
<script src="{{ asset('js/absences.js') }}" defer></script>
<script src="{{ asset('js/activities.js') }}" defer></script>
<script src="{{ asset('js/charges.js') }}" defer></script>
<script src="{{ asset('js/configs.js') }}" defer></script>
<script src="{{ asset('js/dashboard.js') }}" defer></script>
<script src="{{ asset('js/dragdrop.js') }}" defer></script>
<script src="{{ asset('js/info.js') }}" defer></script>
<script src="{{ asset('js/log_activity.js') }}" defer></script>
<script src="{{ asset('js/login.js') }}" defer></script>
<script src="{{ asset('js/phases.js') }}" defer></script>
<script src="{{ asset('js/planning.js') }}" defer></script>
<script src="{{ asset('js/tasks.js') }}" defer></script>
<script src="{{ asset('js/users.js') }}" defer></script>
<script src="{{ asset('js/work_days.js') }}" defer></script>